import { DatabaseContextProvider } from "@/services";
import "../globals.scss";
import { Footer, NavBar } from "@/components";
import { Khand } from "next/font/google";
import bg from "../../../public/background.png";
import Favicon from "../../../public/metadata/favicon.ico";
import styles from "./auth.module.scss";

const khand = Khand({ subsets: ["latin"], weight: "400" });

export const metadata = {
	title: "Smagen af Øl",
	description: "Generated by create next app",
	icons: [{ rel: "icon", url: Favicon.src }],
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body
				style={{
					backgroundImage: `url(${bg.src})`,
					height: "100%",
				}}
				className={`${khand.className}`}
			>
				<main className={styles.main}>
					<NavBar />
					{children}
					<Footer attach />
				</main>
			</body>
		</html>
	);
};

export default AuthLayout;
