import { Footer, NavBar } from "@/components";
import { DatabaseContextProvider } from "@/services";
import { Khand } from "next/font/google";

const khand = Khand({ subsets: ["latin"], weight: "400" });

export const metadata = {
	title: "Smagen af Øl",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body style={{ fontSize: "X-Large" }} className={khand.className}>
				<DatabaseContextProvider>{children}</DatabaseContextProvider>
				<Footer />
			</body>
		</html>
	);
}
