@startuml er_diagram

entity Brewery {
    PK | id: cuid <<generated>>
    --
    * name: text
    description: text
}

entity Beer {
    PK | id: cuid <<generated>>
    --
    * breweryName: text <<FK>>
    * name: text
    description: text
    * type: text
    * vol: decimal
    ibu: int
    * size: int
    image_url: text
}

entity Distillery {
    PK | id: cuid <<generated>>
    --
    * name: text
    description: text
}

entity Spirit {
    PK | id: cuid <<generated>>
    --
    * distilleryName: text <<FK>>
    * name: text
    description: text
    * type: text
    * vol: decimal
    * size: int
    image_url: text
}

entity BeerStock {
    PK | id: cuid <<generated>>
    --
    * beerName: text <<FK>>
    * amount: int
}

entity SpiritStock {
    PK | id: cuid <<generated>>
    --
    * spiritName: text <<FK>>
    * amount: int
}

entity Announcements {
    PK | id: cuid <<generated>>
    --
    * title: text
    * facebookUrl: text
}

entity Admin {
    PK | id: cuid <<generated>>
    --
    * name: text
}

Beer }o--|| Brewery
Spirit }o--|| Distillery

Beer ||--o{ BeerStock
Spirit ||--o{ SpiritStock

BeerStock -[hidden]down-> Announcements
Distillery -[hidden]down-> Admin

@enduml