import { Footer, NavBar } from "@/components";
import { DatabaseContextProvider } from "@/services";
import { Khand } from "next/font/google";
import Favicon from "../../../public/metadata/favicon.ico";
import "../globals.scss";

const khand = Khand({ subsets: ["latin"], weight: "400" });

export const metadata = {
	title: "Smagen af Øl",
	description: "Generated by Next.js",
	icons: [{ rel: "icon", url: Favicon.src }],
};

export default function AdminLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${khand.className}`}>
				<NavBar push />
				<DatabaseContextProvider>{children}</DatabaseContextProvider>
				<Footer />
			</body>
		</html>
	);
}
