import { DatabaseContextProvider } from "@/services";
import "../globals.scss";
import { Footer, NavBar } from "@/components";
import { Khand } from "next/font/google";
import Favicon from "../../../public/metadata/favicon.ico";
import styles from "./index.module.scss";
import { InfoContextProvider } from "@/services/info/useInfo";

const khand = Khand({ subsets: ["latin"], weight: "400" });

export const metadata = {
	title: "Smagen af Øl",
	description: "Generated by create next app",
	icons: [{ rel: "icon", url: Favicon.src }],
};

const RootLayout = ({
	children,
	random_beer,
	botd,
	announcements,
}: {
	children: React.ReactNode;
	random_beer: React.ReactNode;
	botd: React.ReactNode;
	announcements: React.ReactNode;
}) => {
	return (
		<html lang="en">
			<body className={`${khand.className}`}>
				<NavBar />
				<main className={styles.main}>
					{children}
					<DatabaseContextProvider>
						<InfoContextProvider>
							<div className={styles.grid}>
								{botd}
								{random_beer}
								{announcements}
							</div>
						</InfoContextProvider>
					</DatabaseContextProvider>
				</main>
				<Footer attach />
			</body>
		</html>
	);
};

export default RootLayout;
