import { DatabaseContextProvider } from "@/services";
import "./globals.scss";
import { Footer, NavBar } from "@/components";
import { Khand } from "next/font/google";
import Favicon from "../../../public/metadata/favicon.ico";

const khand = Khand({ subsets: ["latin"], weight: "400" });

export const metadata = {
	title: "Smagen af Øl",
	description: "Generated by create next app",
	icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
	children,
	beer,
}: {
	children: React.ReactNode;
	beer: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={khand.className}>
				<DatabaseContextProvider>
					<NavBar />
					{children}
					{beer}
				</DatabaseContextProvider>
				<Footer />
			</body>
		</html>
	);
}
