import { DatabaseContextProvider } from "@/services";
import "../globals.scss";
import { Footer, NavBar } from "@/components";
import { Khand } from "next/font/google";
import bg from "../../../public/background.png";
import Favicon from "../../../public/metadata/favicon.ico";

const khand = Khand({ subsets: ["latin"], weight: "400" });

export const metadata = {
	title: "Smagen af Øl",
	description: "Generated by create next app",
	icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				style={{
					backgroundImage: `url(${bg.src})`,
					height: "100%",
				}}
				className={`${khand.className}`}
			>
				<NavBar />
				<DatabaseContextProvider>{children}</DatabaseContextProvider>
				<Footer attach />
			</body>
		</html>
	);
}
