import { NavBar } from "@/components";
import { DatabaseContextProvider } from "@/services";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function ExploreLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<>
			<NavBar push />
			{children}
		</>
	);
}
